name: Chat with GPT

on: [push]

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Send message to GPT
      run: |
        curl -X POST \
        https://api.openai.com/v1/chat/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.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 }}" \
        -d '{
             "model": "gpt-3.5-turbo",
             "messages": [{"role": "user", "content": "Say this is a test!"}],
             "temperature": 0.7
           }'
      env:
        OPENAI_KEY: ${{ secrets.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 }}